# Application settings
spring.application.name=observability-lab

# Server settings
server.port=8080

# Observability settings
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.opentelemetry.resource-attributes.service.name=observability-lab
management.opentelemetry.resource-attributes.service.namespace=auth-lab
management.opentelemetry.resource-attributes.service.version=0.0.1
management.opentelemetry.resource-attributes.deployment.environment=local
management.opentelemetry.tracing.export.otlp.endpoint=http://tempo:4318/v1/traces